# Generated by Django 5.2 on 2025-04-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255)),
                ('store', models.CharField(choices=[('google_play', 'Google Play'), ('app_store', 'App Store')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('app_name', models.CharField(max_length=255)),
                ('last_updated', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppToMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255)),
                ('store', models.CharField(choices=[('google_play', 'Google Play'), ('app_store', 'App Store')], max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('app_id', 'store')},
            },
        ),
    ]
